### ISSUE TITLE
Title exceeding document boundaries

### ISSUE THREAD

**Issue by Stefan-Wagner** [atp-mipt/jsyntrax#46]
This is my spec file:
`line ('for', '(', loop (opt (opt('Typ'), '/Bezeichner', '=', '/Anweisung'), ","), ';', opt ('/boolscher Ausdruck'), ';', opt (loop ('/Anweisung', ','), ), ')', '/Anweisung')
`
and this the command to produce an PNG with title (the problem exists with SVG output, too:)
`./jsyntrax/target/appassembler/bin/syntrax -title "klassische for-Loop (jsyntrax, cmd-2)" kl-for-loop2.spec -o kl-for-loop2.png`

and this the resulting image: 
![kl-for-loop2](https://user-images.githubusercontent.com/959927/114285539-3744fe00-9a58-11eb-8cc3-fc63ee769ea9.png)

The title starts left of the document and is therefore cut off. I did not change the .ini-files.

**Comment by inponomarev** [comment]
The problem is reproduced!

**Comment by inponomarev** [comment]
Try SVG: it seems that it work OK with SVG, though.

**Comment by Stefan-Wagner** [comment]
As noted above, the problem exists in SVG for me, too.
(Again, Linux in Xubuntu-20.04 flavor).
